=== Tritbool/Heap4CS/Test Bibli/XSD/grid.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://liktek.fr/likacoustik/grid"
           xmlns="http://liktek.fr/likacoustik/grid"
           elementFormDefault="qualified">



    <xs:element name="grid" type="Grid"/>
    
    <xs:complexType name="Grid">
        <xs:sequence>
            <xs:element name="measure" type="Measure" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Measure">
        <xs:sequence>
            <xs:element name="ref" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="measureType" type="MeasureType" minOccurs="1" maxOccurs="1" />
            <xs:element name="measureNature" type="MeasureNature" minOccurs="1" maxOccurs="1" />
            <xs:element name="origin" type="Location" minOccurs="1" maxOccurs="1" />
            <xs:element name="reception" type="Location" minOccurs="1" maxOccurs="1" />
            <xs:element name="equipment" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="indice" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="value" type="Value"  minOccurs="1" maxOccurs="1"/>
            <xs:element name="constat" type="Constat" minOccurs="1" maxOccurs="1" />
            <xs:element name="comment" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="MeasureType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Bruit d'impact"/>
            <xs:enumeration value="Isolement"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="MeasureNature">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Horizontal"/>
            <xs:enumeration value="Vertical"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="Location">
        <xs:sequence>
            <xs:element name="building" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="floor" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="flat" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="room" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Value">
        <xs:sequence>
            <xs:element name="required" type="Scale"  minOccurs="0" maxOccurs="1"/>
            <xs:element name="measured" type="Scale"  minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:simpleType name="Scale">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="130"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Constat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="C"/>
            <xs:enumeration value="CT"/>
            <xs:enumeration value="NC"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== Tritbool/Heap4CS/Test Bibli/XML/testGrid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:grid
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://liktek.fr/likacoustik/grid'
    xsi:schemaLocation='http://liktek.fr/likacoustik/grid file:/Users/gauthierlyan/NetBeansProjects/LikacoustikXML/src/java/grid.xsd'>
    
    <ns1:measure>
        <ns1:ref>C-T3</ns1:ref>
        <ns1:measureType>Isolement</ns1:measureType>
        <ns1:measureNature>Horizontal</ns1:measureNature>
        <ns1:origin>
            <ns1:building>Tour Eiffel</ns1:building>
            <ns1:floor>2</ns1:floor>
            <ns1:flat>Chez Roger</ns1:flat>
            <ns1:room>Salle Ã  manger</ns1:room>
        </ns1:origin>
        <ns1:reception>
            <ns1:building>Tour Eiffel</ns1:building>
            <ns1:floor>2</ns1:floor>
            <ns1:flat>Chez Roger</ns1:flat>
            <ns1:room>Salle de bain</ns1:room>
        </ns1:reception>
        <ns1:equipment>Mesureur acoustique classique</ns1:equipment>
        <ns1:indice>Ct, dnd</ns1:indice>
        <ns1:value>
            <ns1:required>30</ns1:required>
            <ns1:measured>37</ns1:measured>
        </ns1:value>
        <ns1:constat>C</ns1:constat>
        <ns1:comment>RAS</ns1:comment>
    </ns1:measure>
    
    
    <ns1:measure>
        <ns1:ref>C-T1</ns1:ref>
        <ns1:measureType>Bruit d'impact</ns1:measureType>
        <ns1:measureNature>Vertical</ns1:measureNature>
        <ns1:origin>
            <ns1:building>Tour Montparnasse</ns1:building>
            <ns1:floor>30</ns1:floor>
            <ns1:flat>Chez Paul</ns1:flat>
            <ns1:room>Chambre 1</ns1:room>
        </ns1:origin>
        <ns1:reception>
            <ns1:building>Tour Montparnasse</ns1:building>
            <ns1:floor>29</ns1:floor>
            <ns1:flat>Chez Simone</ns1:flat>
            <ns1:room>Cuisine</ns1:room>
        </ns1:reception>
        <ns1:equipment>Mesureur acoustique classique</ns1:equipment>
        <ns1:indice>Ct, dnd</ns1:indice>
        <ns1:value>
            <ns1:required>40</ns1:required>
            <ns1:measured>30</ns1:measured>
        </ns1:value>
        <ns1:constat>NC</ns1:constat>
        <ns1:comment>Bruit trop peu ressenti</ns1:comment>
    </ns1:measure>
    
    <ns1:measure>
        <ns1:ref>C-R12</ns1:ref>
        <ns1:measureType>Isolement</ns1:measureType>
        <ns1:measureNature>Vertical</ns1:measureNature>
        <ns1:origin>
            <ns1:building>ISTIC</ns1:building>
            <ns1:floor>2</ns1:floor>
            <ns1:flat></ns1:flat>
            <ns1:room>Salle 213</ns1:room>
        </ns1:origin>
        <ns1:reception>
            <ns1:building>ISTIC</ns1:building>
            <ns1:floor>2</ns1:floor>
            <ns1:flat></ns1:flat>
            <ns1:room>Salle 215</ns1:room>
        </ns1:reception>
        <ns1:equipment>Mesureur acoustique classique</ns1:equipment>
        <ns1:indice>Ct, dnd</ns1:indice>
        <ns1:value>
            <ns1:required>40</ns1:required>
            <ns1:measured>56</ns1:measured>
        </ns1:value>
        <ns1:constat>C</ns1:constat>
        <ns1:comment>RAS</ns1:comment>
    </ns1:measure>  
    

</ns1:grid>
