=== Tritbool/Heap4CS/Test Bibli/XSD/standards.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://liktek.fr/likacoustik/standards"
           xmlns="http://liktek.fr/likacoustik/standards"
           elementFormDefault="qualified">
    
    
    
    <xs:element name="standards" type="Standards" />
    <xs:complexType name="Standards">
        <xs:sequence>
            <xs:element name="header" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="standard" type="Standard" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:complexType name="Standard">
        <xs:sequence>
            <xs:element name="reference" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="limit" type="Limit" minOccurs="1" maxOccurs="1"/>
            <xs:element name="value" type="Value" minOccurs="1" maxOccurs="1"/>
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="unit" type="Unit" use="optional"/>
    </xs:complexType>

  <xs:simpleType name="Limit">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Maximum"/>
      <xs:enumeration value="Minimum"/>
    </xs:restriction>
  </xs:simpleType>
  
    <xs:simpleType name="Value">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="130"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Unit">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Db"/>
            <xs:enumeration value="Db FS"/>
            <xs:enumeration value="Hz"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
</xs:schema>

=== Tritbool/Heap4CS/Test Bibli/XML/testStandards.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:standards
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://liktek.fr/likacoustik/standards'
    xsi:schemaLocation='http://liktek.fr/likacoustik/standards file:/Users/gauthierlyan/NetBeansProjects/LikacoustikXML/src/java/standards.xsd'>
    
    <ns1:header>Liste des normes acoustiques en vigueur au 1 janvier 2016</ns1:header>
    
    <ns1:standard unit="Db">
        <ns1:reference>103-TRD</ns1:reference>
        <ns1:value>45</ns1:value>
    </ns1:standard>

    <ns1:standard unit="Db FS">
        <ns1:reference>105-TRD</ns1:reference>
        <ns1:value>34</ns1:value>
    </ns1:standard>
    
    <ns1:standard unit="Db">
        <ns1:reference>119-TRD</ns1:reference>
        <ns1:value>45</ns1:value>
    </ns1:standard>



</ns1:standards>
